version: "3.9"

services:
  # user-center-umi:
  #   restart: "always"
  #   build:
  #     context: ./user-center-umi
  #     dockerfile: docker/Dockerfile
  #   image: user-center-umi
  #   networks:
  #     - frontend

  user-center-go:
    restart: "always"
    build:
      context: ./user-center-go
      dockerfile: docker/Dockerfile
    image: user-center-go
    environment:
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:?mongo url is required}
      DB: ${DB:-uc}
      K: ${K:?iv key is required}
    networks:
      - backend
    depends_on:
      - mongo

  user-center:
    restart: "always"
    image: user-center-route
    container_name: user-center-route
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
    ports:
      - 8001:80

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
