version: "3.9"

services:
  user-center-umi:
    restart: "always"
    build:
      context: ./user-center-umi
      dockerfile: docker/Dockerfile
    image: ngekaworu/user-center-umi
    container_name: user-center-umi
    networks:
      - frontend

  user-center-go:
    restart: "always"
    build:
      context: ./user-center-go
      dockerfile: docker/Dockerfile
    image: ngekaworu/user-center-go
    container_name: user-center-go
    environment:
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:?mongo url is required}
      DB: ${DB:-user-center}
      K: ${K:?iv key is required}
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    name: backend
    driver: bridge
  frontend:
    name: frontend
    driver: bridge
