version: "3.9"

services:
  user-center-umi:
    build:
      context: ./user-center-umi
      dockerfile: Dockerfile
    image: user-center-umi
    environment:
      BRANCH: ${BRANCH:-master}

  user-center-go:
    build:
      context: ./user-center-go
      dockerfile: Dockerfile
    image: user-center-go
    environment:
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:-mongodb://mongo:27017}
      DB: ${DB:-uc}
      K: ${K:-f3fa39nui89Wi707}
    networks:
      - backend
    depends_on:
      - mongo

  user-center:
    image: nginx:stable-alpine
    container_name: user-center
    depends_on:
      - user-center-umi
      - user-center-go
    volumes:
      - $PWD/user-center.nginx.conf:/etc/nginx/conf.d/
    networks:
      - backend
      - frontend
    ports:
      - 80:80

networks:
  backend:
    name: backend
    driver: bridge
