version: "3.9"

services:
  user-center-umi:
    build:
      context: user-center-umi
      dockerfile: docker/Dockerfile.dev
    image: user-center-umi:dev
    container_name: user-center-umi
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:-master}
    networks:
      - backend
    ports:
      - 8001:80
    volumes:
      - ~/.ssh:/root/.ssh

  user-center-go:
    build:
      context: user-center-go
      dockerfile: docker/Dockerfile.dev
    image: user-center-go:dev
    container_name: user-center-go
    stdin_open: true
    tty: true
    environment:
      BRANCH: ${BRANCH:-master}
      ADDR: ${ADDR:-:80}
      DBINIT: ${DBINIT:-false}
      MONGO: ${MONGO:-mongodb://mongo:27017}
      DB: ${DB:-uc}
      K: ${K:-f3fa39nui89Wi707}
    volumes:
      - ~/.ssh:/root/.ssh
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    name: backend
    driver: bridge
