version: "3.9"

services:
  user-center-umi:
    build:
      context: ./user-center-umi
      dockerfile: Dockerfile
    image: user-center-umi
    environment:
      BRANCH: ${BRANCH:-master}

  user-center-go:
    build:
      context: ./user-center-go
      dockerfile: Dockerfile
    image: user-center-go
    environment:
      BRANCH: ${BRANCH:-master}
      ADDR: ${ADDR:-':80'}
      DBINIT: ${DBINIT:-'false'}
      MONGO: ${MONGO:?'MONGO url is required'}
      DB: ${DB:'uc'}
      K: ${K:?'iv key is required'}
    networks:
      - backend
    depends_on:
      - mongo

  user-center:
    image: nginx:stable-alpine
    container_name: user-center
    depends_on:
      - user-center-umi
      - user-center-go
    volumes:
      - $PWD/user-center.nginx.conf:/etc/nginx/conf.d/
    networks:
      - backend
      - frontend
    port:
      - 80:80

networks:
  backend:
    name: backend
    driver: bridge
